01:19:59.764 Running build in Washington, D.C., USA (East) – iad1
01:19:59.765 Build machine configuration: 2 cores, 8 GB
01:19:59.776 Cloning github.com/druaiconsulting-design/dru-clear-app (Branch: main, Commit: 2fce2a2)
01:19:59.777 Skipping build cache, deployment was triggered without cache.
01:20:00.841 Cloning completed: 1.065s
01:20:01.297 Running "vercel build"
01:20:02.047 Vercel CLI 51.6.1
01:20:02.691 Detected `pnpm-lock.yaml` version 9 generated by pnpm@10.x with package.json#packageManager pnpm@10.4.1+sha512.c753b6c3ad7afa13af388fa6d808035a008e30ea9993f58c6663e2bc5ff21679aa834db094987129aa4d488b86df57f7b634981b2f827cdcacc698cc0cfb88af
01:20:02.691 Running "install" command: `pnpm install --no-frozen-lockfile`...
01:20:04.892 (node:73) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
01:20:04.893 (Use `node --trace-deprecation ...` to show where the warning was created)
01:20:05.236 Progress: resolved 0, reused 0, downloaded 1, added 0
01:20:06.236 Progress: resolved 54, reused 0, downloaded 53, added 0
01:20:07.250 Progress: resolved 91, reused 0, downloaded 78, added 0
01:20:08.250 Progress: resolved 204, reused 0, downloaded 188, added 0
01:20:09.251 Progress: resolved 219, reused 0, downloaded 203, added 0
01:20:10.263 Progress: resolved 307, reused 0, downloaded 269, added 0
01:20:11.264 Progress: resolved 362, reused 0, downloaded 302, added 0
01:20:12.267 Progress: resolved 507, reused 0, downloaded 451, added 0
01:20:13.279 Progress: resolved 683, reused 0, downloaded 597, added 0
01:20:13.721 Packages: +652
01:20:13.722 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
01:20:14.285 Progress: resolved 738, reused 0, downloaded 652, added 110
01:20:15.287 Progress: resolved 738, reused 0, downloaded 652, added 333
01:20:16.288 Progress: resolved 738, reused 0, downloaded 652, added 339
01:20:17.290 Progress: resolved 738, reused 0, downloaded 652, added 502
01:20:18.229 Progress: resolved 738, reused 0, downloaded 652, added 652, done
01:20:18.972  WARN  Issues with peer dependencies found
01:20:18.972 .
01:20:18.972 └─┬ @builder.io/vite-plugin-jsx-loc 0.1.1
01:20:18.972   └── ✕ unmet peer vite@"^4.0.0 || ^5.0.0": found 7.1.9
01:20:18.976 
01:20:18.977 dependencies:
01:20:18.977 + @hookform/resolvers 5.2.2
01:20:18.977 + @radix-ui/react-accordion 1.2.12
01:20:18.977 + @radix-ui/react-alert-dialog 1.1.15
01:20:18.978 + @radix-ui/react-aspect-ratio 1.1.7
01:20:18.978 + @radix-ui/react-avatar 1.1.10
01:20:18.978 + @radix-ui/react-checkbox 1.3.3
01:20:18.978 + @radix-ui/react-collapsible 1.1.12
01:20:18.978 + @radix-ui/react-context-menu 2.2.16
01:20:18.979 + @radix-ui/react-dialog 1.1.15
01:20:18.979 + @radix-ui/react-dropdown-menu 2.1.16
01:20:18.979 + @radix-ui/react-hover-card 1.1.15
01:20:18.979 + @radix-ui/react-label 2.1.7
01:20:18.979 + @radix-ui/react-menubar 1.1.16
01:20:18.979 + @radix-ui/react-navigation-menu 1.2.14
01:20:18.980 + @radix-ui/react-popover 1.1.15
01:20:18.980 + @radix-ui/react-progress 1.1.7
01:20:18.980 + @radix-ui/react-radio-group 1.3.8
01:20:18.980 + @radix-ui/react-scroll-area 1.2.10
01:20:18.980 + @radix-ui/react-select 2.2.6
01:20:18.980 + @radix-ui/react-separator 1.1.7
01:20:18.981 + @radix-ui/react-slider 1.3.6
01:20:18.981 + @radix-ui/react-slot 1.2.3
01:20:18.981 + @radix-ui/react-switch 1.2.6
01:20:18.981 + @radix-ui/react-tabs 1.1.13
01:20:18.981 + @radix-ui/react-toggle 1.1.10
01:20:18.981 + @radix-ui/react-toggle-group 1.1.11
01:20:18.986 + @radix-ui/react-tooltip 1.2.8
01:20:18.987 + @supabase/supabase-js 2.105.1
01:20:18.987 + axios 1.12.2
01:20:18.987 + class-variance-authority 0.7.1
01:20:18.987 + clsx 2.1.1
01:20:18.987 + cmdk 1.1.1
01:20:18.988 + embla-carousel-react 8.6.0
01:20:18.988 + express 4.21.2
01:20:18.988 + framer-motion 12.23.22
01:20:18.988 + input-otp 1.4.2
01:20:18.988 + jspdf 4.2.1
01:20:18.988 + lucide-react 0.453.0
01:20:18.989 + nanoid 5.1.6
01:20:18.989 + next-themes 0.4.6
01:20:18.989 + react 19.2.1
01:20:18.989 + react-day-picker 9.11.1
01:20:18.989 + react-dom 19.2.1
01:20:18.989 + react-hook-form 7.64.0
01:20:18.989 + react-resizable-panels 3.0.6
01:20:18.989 + recharts 2.15.4
01:20:18.990 + sonner 2.0.7
01:20:18.990 + streamdown 1.4.0
01:20:18.990 + tailwind-merge 3.3.1
01:20:18.990 + tailwindcss-animate 1.0.7
01:20:18.990 + vaul 1.1.2
01:20:18.990 + wouter 3.7.1
01:20:18.990 + zod 4.1.12
01:20:18.990 
01:20:18.990 devDependencies:
01:20:18.991 + @builder.io/vite-plugin-jsx-loc 0.1.1
01:20:18.991 + @tailwindcss/typography 0.5.19
01:20:18.991 + @tailwindcss/vite 4.1.14
01:20:18.991 + @types/express 4.17.21
01:20:18.991 + @types/google.maps 3.58.1
01:20:18.991 + @types/node 24.7.0
01:20:18.991 + @types/react 19.2.1
01:20:18.992 + @types/react-dom 19.2.1
01:20:18.992 + @vitejs/plugin-react 5.0.4
01:20:18.993 + add 2.0.6
01:20:18.993 + autoprefixer 10.4.21
01:20:18.993 + esbuild 0.25.10
01:20:18.993 + pnpm 10.18.1
01:20:18.993 + postcss 8.5.6
01:20:18.993 + prettier 3.6.2
01:20:18.993 + tailwindcss 4.1.14
01:20:18.993 + tsx 4.20.6
01:20:18.994 + tw-animate-css 1.4.0
01:20:18.994 + typescript 5.6.3
01:20:18.994 + vite 7.1.9
01:20:18.994 + vite-plugin-manus-runtime 0.0.57
01:20:18.994 + vitest 2.1.9
01:20:18.994 
01:20:18.995 ╭ Warning ─────────────────────────────────────────────────────────────────────╮│                                                                              ││   Ignored build scripts: @tailwindcss/oxide, core-js, esbuild.               ││   Run "pnpm approve-builds" to pick which dependencies should be allowed     ││   to run scripts.                                                            ││                                                                              │╰──────────────────────────────────────────────────────────────────────────────╯
01:20:18.995 
01:20:19.000 Done in 14.5s using pnpm v10.4.1
01:20:19.610 [36mvite v7.1.9 [32mbuilding for production...[36m[39m
01:20:19.671 [33m[1m(!) %VITE_ANALYTICS_ENDPOINT% is not defined in env variables found in /index.html. Is the variable mistyped?[22m[39m
01:20:19.673 [33m[1m(!) %VITE_ANALYTICS_WEBSITE_ID% is not defined in env variables found in /index.html. Is the variable mistyped?[22m[39m
01:20:19.704 <script src="%VITE_ANALYTICS_ENDPOINT%/umami"> in "/index.html" can't be bundled without type="module" attribute
01:20:19.745 transforming...
01:20:21.019 [32m✓[39m 40 modules transformed.
01:20:21.024 [31m✗[39m Build failed in 1.38s
01:20:21.025 [31merror during build:
01:20:21.025 [31m[vite]: Rollup failed to resolve import "react-router-dom" from "/vercel/path0/client/src/pages/AdminOrg.tsx".
01:20:21.025 This is most likely unintended because it can break your application at runtime.
01:20:21.025 If you do want to externalize this module explicitly add it to
01:20:21.025 `build.rollupOptions.external`[31m
01:20:21.026     at viteLog (file:///vercel/path0/node_modules/.pnpm/vite@7.1.9_@types+node@24.7.0_jiti@2.6.1_lightningcss@1.30.1_tsx@4.20.6/node_modules/vite/dist/node/chunks/dep-Chhhsdoe.js:33989:57)
01:20:21.026     at file:///vercel/path0/node_modules/.pnpm/vite@7.1.9_@types+node@24.7.0_jiti@2.6.1_lightningcss@1.30.1_tsx@4.20.6/node_modules/vite/dist/node/chunks/dep-Chhhsdoe.js:34025:73
01:20:21.026     at onwarn (file:///vercel/path0/node_modules/.pnpm/@vitejs+plugin-react@5.0.4_vite@7.1.9_@types+node@24.7.0_jiti@2.6.1_lightningcss@1.30.1_tsx@4.20.6_/node_modules/@vitejs/plugin-react/dist/index.js:55:7)
01:20:21.026     at file:///vercel/path0/node_modules/.pnpm/vite@7.1.9_@types+node@24.7.0_jiti@2.6.1_lightningcss@1.30.1_tsx@4.20.6/node_modules/vite/dist/node/chunks/dep-Chhhsdoe.js:34025:28
01:20:21.026     at onRollupLog (file:///vercel/path0/node_modules/.pnpm/vite@7.1.9_@types+node@24.7.0_jiti@2.6.1_lightningcss@1.30.1_tsx@4.20.6/node_modules/vite/dist/node/chunks/dep-Chhhsdoe.js:34020:63)
01:20:21.027     at onLog (file:///vercel/path0/node_modules/.pnpm/vite@7.1.9_@types+node@24.7.0_jiti@2.6.1_lightningcss@1.30.1_tsx@4.20.6/node_modules/vite/dist/node/chunks/dep-Chhhsdoe.js:33821:4)
01:20:21.028     at file:///vercel/path0/node_modules/.pnpm/rollup@4.52.4/node_modules/rollup/dist/es/shared/node-entry.js:20937:32
01:20:21.028     at Object.logger [as onLog] (file:///vercel/path0/node_modules/.pnpm/rollup@4.52.4/node_modules/rollup/dist/es/shared/node-entry.js:22823:9)
01:20:21.029     at ModuleLoader.handleInvalidResolvedId (file:///vercel/path0/node_modules/.pnpm/rollup@4.52.4/node_modules/rollup/dist/es/shared/node-entry.js:21567:26)
01:20:21.029     at file:///vercel/path0/node_modules/.pnpm/rollup@4.52.4/node_modules/rollup/dist/es/shared/node-entry.js:21525:26[39m
01:20:21.077 Error: Command "vite build" exited with 1
